### ISSUE TITLE
execution_date no longer exists in task_instance table

### ISSUE THREAD

**Issue by kasiaowczarz** [aws-samples/amazon-mwaa-examples#17]
In version 2.2.2 the code [here](https://github.com/aws-samples/amazon-mwaa-examples/blob/main/usecases/metadata-migration/2.0.2-2.2.2/export_data.py#L58) should be updated from:
`r.execution_date = ti.execution_date`
to
`r.run_id = ti.run_id`

---
execution_date column update: https://github.com/apache/airflow/pull/19593

**Comment by umaragu** [comment]
Thank you for opening up the issue. The export script you have in the link is supposed to be run in 2.0.2 environment to migrate to 2.2.2. Are you facing issue when running in 2.0.2?
