### ISSUE TITLE
export data DAG running into errors

### ISSUE THREAD

**Issue by kartiknooli** [aws-samples/amazon-mwaa-examples#18]
the export data DAG keeps failing at the `def export_active_dags()` step. the `pause_dags()` task completes and all the active DAGs are paused. and then the DAG fails with the error `FileNotFoundError: [Errno 2] No such file or directory: 's3://mys3-bucket/mwaa-migration-test/active_dags.csv'`.
As a result of this, when the DAG fails, all my active DAGs remain in a paused state and I have to unpause all of them. Am I missing something?

**Comment by umaragu** [comment]
Thank you for opening the issue. Please make sure you have smart_open in your requirements.txt and using `from smart_open import open` in the imports. Let me know if you still run into issues

**Comment by kartiknooli** [comment]
thanks @umaragu. do you know if i can update the requirements.txt file for an existing mwaa env or can I only do it before spinning up a new mwaa env? coz i am getting a `ModuleNotFoundError: No module named 'smart_open'` error when I try to update the requirements file and upload it to the same s3 location.

**Comment by umaragu** [comment]
Please check the Step 5 of the documentation [here](https://docs.aws.amazon.com/mwaa/latest/migrationguide/migrating-to-new-mwaa.html#migrating-to-new-mwaa-exporting-metadatadb). If you have a requirements.txt, You will need to add the two additional modules in this Github repo to it.

**Comment by kartiknooli** [comment]
yes, i added those modules to my existing requirements.txt file and then ran into that issue i mentioned above.

**Comment by umaragu** [comment]
This issue is resolved from a separate conversation. Closing the issue.
