### ISSUE TITLE
add metadata-migration for new version 2.6.3

### ISSUE THREAD

**Issue by skpune** [aws-samples/amazon-mwaa-examples#53]
There is a new MWAA version 2.6.3 available as [announced on Aug 10th, see also [[MWAA versions](https://docs.aws.amazon.com/mwaa/latest/userguide/airflow-versions.html)]
It would be helpful to have adapted migration DAGs, updated with the newer version of airflow 2.6.3.

**Comment by umaragu** [comment]
@skpune MWAA now supports in-place upgrade. Please check out the blog [here](https://aws.amazon.com/blogs/big-data/introducing-in-place-version-upgrades-with-amazon-mwaa/) for more details.

**Comment by manugarri** [comment]
+1 to this, for some of us, migrating in place is not an option since we need to test the dags on a newer version, and the airflow mwaa has the version as part of the name (and that is immutable).

**Comment by crupakheti** [comment]
The metadata migration scripts are handled through the [mwaa-dr](https://pypi.org/project/mwaa-dr/) project going forward.
