### ISSUE TITLE
export_data failed due to Negsignal.SIGKILL

### ISSUE THREAD

**Issue by ducquangkstn** [aws-samples/amazon-mwaa-examples#60]
I am exporting data from 2.0.2 to 2.4.3.

I run the DAG `export_data` and it failed to export 

```
Task exited with return code Negsignal.SIGKILL
```

Adding logger to this DAG and it failed to export task_instance.

**Comment by crupakheti** [comment]
Closing this issue for now, please reopen it if you need further assistance. Thank you!
