### ISSUE TITLE
Create variable for VPC Endpoint creation if already created  

### ISSUE THREAD

**Issue by skpune** [aws-samples/amazon-mwaa-examples#76]
Hi Team,

We are encountering an issue while deploying the start-stop solution in an account that has multiple MWAA environments. When we try to deploy the start-stop solution for another environment, the CloudFormation stack creation is failing and going into a rollback state.

The error message we are receiving is:

"Resource handler returned message: "private-dns-enabled cannot be set because there is already a conflicting DNS domain for states.us-east-1.amazonaws.com in the VPC vpc-0d301afa40a5768ca (Service: Ec2, Status Code: 400, Request ID: ccc14144-39f2-4078-b7e4-8f8dfc0b6d26)" (RequestToken: 3dc89c65-c60e-9c5c-6bf8-b261ab1a9fb7, HandlerErrorCode: GeneralServiceException)"

Could you please help us create a variable for the VPC endpoint creation, in case it already exists? This would allow us to handle the conflict and successfully deploy the start-stop solution for the additional MWAA environment.

Please let me know if you need any further information or assistance from our end.

Thanks,
Shubham

**Comment by crupakheti** [comment]
Thank you, @skpune for your feature request! We plan to merge this feature in subsequent PRs.
